-- CREATING  DATABASE FOR EMPLOYEE DATA
create database Employee_Database; 


-- SELECTING EMPLOYEE DATABASE FOR CREATING TABLES
use Employee_Database;


-- CREATING TABLE FOR EMPLOYEE DATAS
create table Employee
( EMPLOYEE_ID int,FIRST_NAME varchar(25),LAST_NAME varchar(25),SALARY int,JOINING_DATE varchar(15),DEPARTMENT varchar(20), primary key (EMPLOYEE_ID) );
-- HERE EMPLOYEE_ID IS PRIMARY KEY

-- INSERTING DATA 
insert into Employee(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT) values
(1,'Venkatesh','s',100000,'08/28/2015','BANKING'),
(2,'Ragavi','P',75000,'08/28/2015','BUSINESS'),
(3,'Gopinath','C',50000,'03/02/2016','PHARMA'),
(4,'Dinesh','G',50000,'03/02/2016','INSURANCE'),
(5,'Saibaba','E',40000,'07/08/2017','SOFTWARE'),
(6,'Hasan','S',29000,'07/08/2017','MANUFACTURE'),
(7,'Divya','P',33000,'07/08/2017','HEALTHCARE'),
(8,'Aravindan','R',40000,'07/08/2017','HEALTHCARE'),
(9,'Satish','MD',45000,'03/02/2016','AUTOMOBILE'),
(10,'Prasanth','PKP',34000,'03/02/2016','INSURANCE'),
(11,'Vijay','R',25689,'03/02/2016','BUSINESS'),
(12,'Selvakumar','K',54789,'03/02/2016','SOFTWARE');


-- CREATING TABLE FOR INCENTIVES
create table Incentives(Employee_Ref_Id int,Incentive_Date varchar(12),Incentive_Amount int ,foreign key(Employee_Ref_Id) references Employee(EMPLOYEE_ID));
-- HERE Employee_Ref_Id IS FOREIGN KEY


-- INSERTING DATA
insert into Incentives(Employee_Ref_Id,Incentive_Date,Incentive_Amount) values
(1,'01-FEB-16',5000),
(2,'01-FEB-16',3000),
(3,'01-FEB-17',4000),
(1,'01-JAN-17',4500),
(2,'01-JAN-17',4500);


-- BEGINNING OF QUERY SECTION
-- 01 GET ALL EMPLOYEE DETAILS FROM EMPLOYEE TABLE
select*from Employee;

-- 02 GET FIRST NAME ,LAST NAME FROM EMPLOYEE TABLE
select FIRST_NAME , LAST_NAME from Employee;

-- 03 GET FIRST NAME FROM EMPLOYEE USING ALIAS NAME "Employee Name"
select FIRST_NAME Employee_Name from Employee; 

-- 04 GET FIRST NAME FROM EMPLOYEE TABLE IN UPPER CASE
select upper(FIRST_NAME) from Employee; 

-- 05 GET FIRST NAME EMPLOYEE TABLE IN LOWER CASE
select lower(FIRST_NAME) from Employee;

-- 06 GET UNIQE DEPARTMENT FROM EMPLOYEE TABLE
select distinct DEPARTMENT from Employee;

-- 07 SELECT 3 CHARACTER OF FIRST NAME FROM EMPLOYEE TABLE
select substring(FIRST_NAME , 1,3) as FIRST_NAME from Employee;

-- 08 GET POSITION OF a FROM Ragavi
select position('a' IN FIRST_NAME ) position_of_a_in_Ragavi  from Employee where EMPLOYEE_ID = 2;

-- 09 FIRST NAME FROM EMPLOYEE TABLE AFTER REMOVING WHITE SPACE FROM RIGHT SIDE
select rtrim(FIRST_NAME) FIRST_NAME from Employee;

-- 10 FIRST NAME FROM EMPLOYEE TABLE AFTER REMOVING WHITE SPACE FROM LEFT SIDE
select ltrim(FIRST_NAME) FIRST_NAME from Employee;

-- 11 GET LENGTH OF FIRST NAME FROM EMPLOYEE TABLE
select length(FIRST_NAME) LENGTH_OF_FIRST_NAME from Employee;

-- 12 GET FIRST NAME FROM EMPLOYEE TABLE AFTER REPLACING 'a' to '$'
select replace(FIRST_NAME,"a","$") from Employee;

-- 13 GET FIRST NAME AND LAST NAME IN SINGLE COLUMN WITH SEPARATED SPACE
select concat(FIRST_NAME," ",LAST_NAME) FULL_NAME from Employee;

-- 14 GET DATE,MONTH,YEAR AS SEPARATE COLUMN FROM JOINING DATE IN EMPLOYEE TABLE 
select
    FIRST_NAME,
    SUBSTRING_INDEX(JOINING_DATE, '/', -1) as JOINING_YEAR,
    SUBSTRING_INDEX(JOINING_DATE, '/', 1) as JOINING_MONTH,
    SUBSTRING_INDEX(SUBSTRING_INDEX(JOINING_DATE, '/', 2), '/', -1) as JOINING_DAY
from
    Employee;

-- 15 FIRST NAME IN EMPLOYEE table AS ASSENDING ORDER
select * from Employee order by FIRST_NAME asc;

-- 16 FIRST NAME IN EMPLOYEE table AS DESENDING ORDER
select * from Employee order by FIRST_NAME desc;

-- 17 GET ALL EMPLOYEE DETAIL FROM EMPLOYEE TABlE AS ASSECNDING ORDER IN FIRST NAME AND DESSENDING ORDER IN SALARY
select * from employee order by FIRST_NAME ASC , SALARY DESC;

-- 18 GET ALL DETAILS OF EMPLOYEE NAMED DINESH
select * from employee where FIRST_NAME='Dinesh'; 

-- 19 GET THE DETAILS OF EMPLOYEE WHO NAME ARE NOT DINESH AND ROY
select * from employee where FIRST_NAME !='Dinesh'and FIRST_NAME != 'Roy'; 

-- 20 GET THE DETAILS OF EMPLOYEE WHO NAME ARE DINESH AND ROY
select * from employee where FIRST_NAME ='Dinesh' or FIRST_NAME = 'Roy'; 

-- 21 GET EMPLOYEE DETAILS WHOS START WITH 'S'
select*from employee where FIRST_NAME like 'S%';

-- 22 GET EMPLOYEE DETAILS WHOS START WITH 'V'
select*from employee where FIRST_NAME like '%v%';

-- 23 GET EMPLOYEE DETAILS WHOS END WITH 'n'
select*from employee where FIRST_NAME like '%n';

-- 24 GET EMPLOYEE DETAILS WHOS END WITH 'n'
select*from employee where FIRST_NAME like '%n'and '____%';

-- 25 GET EMPLOYEE DETAILS WHOS START WITH 'J'
select*from employee where FIRST_NAME like 'J____%';

-- 26 GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHO'S SALARY MORE THAN 60000
select*from employee where SALARY>60000; 

-- 27 GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHO'S SALARY LESS THAN 80000
select*from employee where SALARY<80000; 

-- 28 GET EMPLOYEE DETAILS FROM EMPLOYEE TABLE WHO'S SALARY MORE THAN 50000 AND LESS THAN 80000
select*from employee where SALARY>50000 and SALARY < 80000; 

-- 29 GET THE EMPLOYEE DETAILS IN EMPLOYEE TABLE WHO'S NAME IS VENKATESH AND RAGAVI
select *from employee where FIRST_NAME = 'Venkatesh' or FIRST_NAME='Ragavi'; 

-- 30 GET ALL DETAILS OF EMPLOYEE WHO HAS '%' IN LAST NAME
select * from employee where LAST_NAME='%'; 

-- 31 GET THE LAST NAME FROM EMPLOYEE TABLE AFTER REPLACING @ WITH WHITE SPACE 
select replace(LAST_NAME, '@', ' ') as Modified_Last_Name from Employee;

-- 32 GET DEPARTMENT AND TOTAL SALARY WITH RESPECT TO DEPARTMENT IN EMPLOYEE TABLE 
select DEPARTMENT , sum(SALARY) as TOTAL_SALARY from employee group by DEPARTMENT; 

-- 33 GET DEPARTMENT AND TOTAL SALARY WITH RESPECT TO DEPARTMENT IN EMPLOYEE TABLE IN DESENDING ORDER OF TOTAL SALARY 
select DEPARTMENT , sum(SALARY) AS TOTAL_SALARY from employee group by DEPARTMENT order by sum(SALARY) desc; 

-- 34 GET DEPARTMENT AND NUMBER EMPLOYEE IN DEPARTMENT AND TOTAL SALARY WITH RESPECT TO DEPARTMENT IN EMPLOYEE TABLE IN DESENDING ORDER OF TOTAL SALARY 
select DEPARTMENT , count(EMPLOYEE_ID),sum(SALARY) AS TOTAL_SALARY from employee group by DEPARTMENT order by sum(SALARY) desc; 

-- 35 GET DEPARTMENT WISE AVERAGE SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASSENDING
select DEPARTMENT , avg(SALARY) as AVERAGE_SALARY from employee group by DEPARTMENT order by avg(SALARY) asc;

-- 36 GET DEPARTMENT WISE MAXIMUM SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASSENDING
select DEPARTMENT , max(SALARY) as AVERAGE_SALARY from employee group by DEPARTMENT order by max(SALARY) asc;

-- 37 GET DEPARTMENT WISE MINIMUM SALARY FROM EMPLOYEE TABLE ORDER BY SALARY ASSENDING
select DEPARTMENT , min(SALARY) as AVERAGE_SALARY from employee group by DEPARTMENT order by min(SALARY) asc;

-- 38 SELECT NUMBER OF EMPLOYEE JOINED WITH RESPECT TO YEAR AND MONTH TABLE 
select SUBSTRING_INDEX(JOINING_DATE, '/', -1) AS JOINING_YEAR,
	   SUBSTRING_INDEX(JOINING_DATE, '/', 1) AS JOINING_MONTH,
       COUNT(*) AS EMPLOYEE_COUNT from Employee
group by JOINING_YEAR, JOINING_MONTH order by JOINING_YEAR, JOINING_MONTH;

-- 39 SELECT DEPARTMENT , TOTAL SALARY WITH RESPECT TO TOTAL SALARY GREATER THAN 800000
select DEPARTMENT , sum(SALARY) TOTAL_SALARY from employee group by DEPARTMENT having sum(SALARY)>800000 order by sum(SALARY) desc;

-- 40SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE 
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1 join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id;

-- 41 SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE WHO HAVE INCENTIVE MORE THAN 3000
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1 join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id where Incentive_Amount > 3000;

-- 42 SELECT FIRST NAME AND INCENTIVE AMOUNT FROM EMPLOYEEE AND INCENTIVE TABLE EVEN THEY NOT HAVE INCENTIVE
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1  left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id;

-- 43 SELECT FIRST NAME AND INCENTIVE AMOUNT FROM EMPLOYEEE AND INCENTIVE TABLE EVEN THEY NOT HAVE INCENTIVE THAN PUT 0
select t1.FIRST_NAME , ifnull(t2.Incentive_Amount,0) from employee t1 left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id ;

-- 44 SELECT FIRST NAME , INCENTIVE AMOUNT FROM EMPLOYEE AND INCENTIVE TABLE  WHO GOT INCENTIVE USING LEFT JOIN
select t1.FIRST_NAME , t2.Incentive_Amount from employee t1  left join Incentives t2 on t1.EMPLOYEE_ID=t2.Employee_Ref_Id 
where t2.Incentive_Amount is not null ;

-- 45 select max incentive with respect to employee from employee table and incentive table using sub query
select FIRST_NAME,(select MAX(Incentive_Amount) from Incentives where Employee_Ref_Id = Employee.EMPLOYEE_ID) AS Max_Incentive from Employee;

-- 46 SELECT TOP 2 SALARY FROM THE TABLE
select SALARY TOP_2_SALARY from employee order by SALARY desc limit 2;

-- 47 SELECT TOP N SALARY FROM THE TABLE
select SALARY TOP_10_SALARY from employee order by SALARY desc limit N ; -- REPLACE 'N' BY NEEDED VALUE

-- 48 SELECT 2ND HIGHEST SALARY FROM THE TABLE
select SALARY 2ND_HIGHEST_SALARY from employee limit 1 offset 1 ;

-- 49 SELECT Nth HIGHEST SALARY FROM THE TABLE
select SALARY Nth_HIGHEST_VALUE from employee limit 1 offset N-1 ; -- REPLACE 'N' BY NEEDED VALUE
